### ISSUE TITLE
The example does not work

### ISSUE THREAD

**Issue by qocharian** [SmartEngines/SmartIDReader-Telegram-Bot#1]
Hello! Thank you for your hard work! I am writing a thesis and I want to use your development! But when running the example, an error

Traceback (most recent call last):
  File "/home/user/src/SmartIDReader-Telegram-Bot-master/pySmartIdEngine.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

**Comment by qocharian** [comment]
I even ran this on docker, but the error remains:




During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "smart_idreader_telegram_bot.py", line 34, in <module>
    import pySmartIdEngine as se  # Smart IDReader by Smart Engines
  File "/pySmartIdEngine.py", line 17, in <module>
    _pySmartIdEngine = swig_import_helper()
  File "/pySmartIdEngine.py", line 16, in swig_import_helper
    return importlib.import_module('_pySmartIdEngine')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
root@abf8939882d3:/# ls
__pycache__          bin   bundle_mock_smart_idreader.zip  etc   lib    media  opt   pySmartIdEngine.py  root  sbin                            srv  tmp  var
_pySmartIdEngine.so  boot  dev                             home  lib64  mnt    proc  requirenmants       run   smart_idreader_telegram_bot.py  sys  usr
